# config/pins.yaml
# GPIO pin configuration (BCM numbering)

motor_pins:
  left: [6, 13, 19, 26]
  right: [12, 16, 20, 21]

# FIX: pins 14/15 are not real

ultrasonic_pins:
  front_left:
    trig: 14
    echo: 15
  front_right:
    trig: 27
    echo: 17
  rear_left:
    trig: 9
    echo: 10
  rear_right:
    trig: 24
    echo: 23
