# config/pins.yaml
motor_pins:
  left:  [6, 13, 19, 26]      # back to IN1,IN2,IN3,IN4
  right: [12, 16, 20, 21]

ultrasonic_pins:           # (unchanged)
  top_left:     {trig: 17, echo: 4}
  top_right:    {trig: 22, echo: 27}
  bottom_left:  {trig: 23, echo: 18}
  bottom_mid:   {trig: 25, echo: 24}
  bottom_right: {trig: 7,  echo: 8}

led_pins:                  # (unchanged)
  sanitize: 10
  robot_on: 9
  indicator: 11